services:
  - type: web
    name: mindtrack-ai
    plan: free
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --chdir mindtrack_backend mindtrack_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
