# Generated by Django 4.2.13 on 2026-06-28 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emotion', models.CharField(default='neutral', max_length=50)),
                ('sentiment', models.CharField(default='neutral', max_length=10)),
                ('mood_score', models.IntegerField()),
                ('wellness_suggestion', models.TextField(blank=True, null=True)),
                ('crisis_detected', models.BooleanField(default=False)),
                ('gemini_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('analysis_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='journal.journalentry')),
            ],
        ),
    ]
