# Generated by Django 4.2.13 on 2026-06-28 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('average_mood_score', models.FloatField(blank=True, null=True)),
                ('mood_trend', models.CharField(blank=True, max_length=20, null=True)),
                ('week_summary', models.TextField(blank=True, null=True)),
                ('weekly_suggestion', models.TextField(blank=True, null=True)),
                ('entries_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
